### PR TITLE
Secondary and Spawn Shopkeeps

### PR DESCRIPTION
**Pull request by TheOmniAdam**
Adding Secondary and Spawn Shopkeeps

### CODE REVIEW

**Comment by TheOmniAdam** [comment]
Updated item names to match the new standard. Please let me know if these shop keeps are in line with expectation or have too much of X, Y or Z, etc. It was mentioned it could be implemented that multipliers on sell only items might become a method to create maniacs so in preparation some of these shopkeep have such items/properties already set. It can, of course, be changed to match any standard presented.

**Comment by TheOmniAdam** [comment]
Hey. just wanted to check if I'm doing anything wrong. Saw other pull requests processed but not mine and wasn't sure if my values were off or I was otherwise not following an expected protocol. 

Thanks

**Comment by TheOmniAdam** [comment]
Again- please let me know what to  change or modify about these shop keeps- this pull request has again been passed up while others are pulled in without an explanation. If I've given them too many items or the dialogue is bad, let me know and I will adjust accordingly. I'd be happy to make more shop keeps but not if my efforts are not helpful to the cause. Thanks.

**Comment by MrMasochism** [comment]
I worked really hard to get a set of shopkeepers which sell items which are balanced and don't break the game or take the point of mining/growing etc out.  Your shopkeepers don't fit in with that at all

**Comment by TheOmniAdam** [comment]
I see that clearly. When the discussion was opened I had envisioned many many diverse shopkeepers that would on the whole make every item available somewhere. I didn't know what kind of inventory each would have so I made it excessive to see how many shop keeps there would be and assumed it could be lessened to accommodate. It's clearly not the vision for shop keeps as there appear to only be a handful of variants on the core ones and I see why that makes these shopkeepers out of place.

**Pull request closed without merging**
