### PR TITLE
shopman2.png skin from Pippa

### PR DESCRIPTION
**Pull request by PippaSmith**
Skin and English/French chat for review

### CODE REVIEW

**Comment by PippaSmith** [comment]
Hi MrM, what does it mean when it says this branch has conflicts that must be resolved? What should I do? Also, someone said to me that because in Pokemon game Pokemart shop keepers are always female, I should just do females. But I figure you want a range?

**Comment by AnonymousRandomPerson** [comment]
You need to pull the current changes into your fork and merge them.

There are male shopkeepers in the Pokémon games. Whoever told you the contrary is wrong.

**Comment by PippaSmith** [comment]
Hi, I did a gnome trader to introduce what might be a fun rare trader type; would you like that sort of thing? I am thinking next of a slick-looking salesman in a striped suit; perhaps a creepy old lady; or would you rather straight-forward types? This is for the spawning pokesellers.

**Comment by MrMasochism** [comment]
Straight-forward types are more useful than strange ones in general.  We need more straight forward than strange anyway

**Comment by PippaSmith** [comment]
Ok. Would you like some more shop keepers with pokeball image on the front or their shirts, like the one in the sample images on the forums?

**Pull request merged**
