### PR TITLE
Master

### PR DESCRIPTION
**Pull request by PippaSmith**
shopboy.png skin and chat from Pippa

### CODE REVIEW

**Comment by MrMasochism** [comment]
If you don't mind refreshing this in light of my latest commit that would be great.  Shop item lookup has changed a bit

**Comment by PippaSmith** [comment]
Hi Mr M, I hope I've changed them properly. I'll double check that I updated my shop item file; I notice too that I had items for sale that are not buyable. Do you need more shopkeepers? Let me know your main needs and I'll work on those.

**Comment by PippaSmith** [comment]
Ah, I can see the shopitem list update I didn't use, so I'll change that now.

**Comment by PippaSmith** [comment]
I changed the chat files in line with the proper format.

**Comment by MrMasochism** [comment]
I think overall we'd be better sticking with the 3 main pokemart sellers rather than add more, but you are welcome to bring your new textures/chat lines into those existing sellers.  We put a lot of effort into trying to get a good spread and reasonable set of items into each of those.  What we aren't keen on is putting really high value items into these pokecenters as common items, especially things like hms/high value tms

**Comment by PippaSmith** [comment]
Ah, ok. So where I have done various male shopkeeper skins, put all the chat lines and various names (Charles, etc) into one json file for main seller. And same for female sellers. I've got four types, basically: men; boys; women; girls. Their chat type is rather different. Would you like four json files with those four to refer to the four skin types? I'll reset them all that way and you can change it to what you prefer if that's not ok.
I'll take out the high value items. I did think that I should change my pokeball multi-sale figure to make it cheaper to buy more than one, rather than more expensive, say 0.9, as it then becomes a disincentive to buy more; I've put 1.1.

**Comment by PippaSmith** [comment]
Hi Mr M, I reduced the chat files to 3 main sellers and one second seller, as I realised my 'women' sellers were secondary sellers. So that leaves men, boys and girls as the three main types. I deleted the extra files. I hope I've done this correctly.

**Comment by MrMasochism** [comment]
This is much better.  The only thing I'm not sure of is having kids as shopkeepers.  Doesn't seem right to me in a pokemart

**Comment by PippaSmith** [comment]
I can make the girl and boy ones ones older, dressed older, and combine them into the male and female existing. So that there would then be only two main seller types; male and female. Would that do?

**Comment by MrMasochism** [comment]
That would be great

**Comment by PippaSmith** [comment]
Hi, I hope I've not been presumptuous. I've combined things and renamed skins and altered skin clothes so that now there are only shopman and shoplady png files, which then become pokemartmain1 and pokemartmain2 json files. The pokemartsecond is left as it was, but I"ve combined the Spanish pokemart json files to match what I did with the English and French. I also put a pokeball on the apron of shopman.png, And with the spanish pokemartsecond json, I combined into one to match the others. I really hope I've not messed up. I was not sure about commas required after each chat and name etc, but went on instinct and removed them. You'll need to check that I've done it right. Now, what I'll do next is some normal spawn skins and some more second seller skins shall I? My question is, if the skins and chat files are combined, that means there will be less range of stuff for sale by them, in other words they'll all sell the same things as each other. Is that a problem?

**Comment by MrMasochism** [comment]
Yeah that's a little bit of a problem.  How about keeping the 3 types of pokemart mains and splitting the male (or female) skins between 2 of them so that we still get 3 types to give enough variation.  I was happy with the set of items for sale between the 3

**Comment by PippaSmith** [comment]
ok shall do.
Want some more of which next mainly? spawn traders or pokemart seconds? I would imagine the latter; i've only done two women for that. I've done a new spawn one, so there's two of each now. And, on same situation as above, i should prob do some male seconds and separate them for diff items again? Sorry if I ask too much; it's just best I know before I go ahead.

**Comment by PippaSmith** [comment]
Forget I said that. I can see the secondary sellers have all the TMS; you would not want alternative list of items I'm sure. Let me know if you do want that split. I've added a secondary seller male skin to it. I was going to split up the pokemartmain1 into two, but instead I'll just add a third set with alternative skins. Easier really, and the more skins the better. You'll get them soon. If I put items for sale that are not as you want, just change them.

**Comment by PippaSmith** [comment]
Oh also, the first set of mains has all males; so no need to split it unless you want. I'll make a third set with females? Or is a mix ok? From what I can see, the way the chat is laid ;out, it pertains to the next skin in the line? Or does the chat and npc's name appear randomly? ie is a female going to be called Mr Prendergast accidentally if it's in the male set? If that's how it works, I'll do a third set female only. Same situation would occur with the secondary seller I added to the list. He is male, the other two female. If that causes a name issue (chat is unimportant to that), I'll split it and make a second secondary json.

**Comment by PippaSmith** [comment]
I've set up the pokemartmain3.json file in english; will do french. If I've put in items that it shouldn't contain please change it. I hope I've done it right.

**Comment by PippaSmith** [comment]
Now going to work on more skins for pokemartmain3 (all female) and pokemartsecond1. Do you want the pokemartsecond1 split into male and female?

**Pull request merged**
