### PR TITLE
Villager seems to not generate with multiple skins

### PR DESCRIPTION
**Pull request by TheOmniAdam**
Removing additional village skins

### CODE REVIEW

**Comment by MrMasochism** [comment]
This is not the right approach.  If there's an issue with them not showing up with multiple skins then let me know and I'll look at fixing it at the other end

**Comment by MrMasochism** [comment]
That said.  What is the issue?  When you say not generating what do you mean?

**Comment by TheOmniAdam** [comment]
When the update launched, I noticed while spawning hundreds of villagers that never once did a Pokemon Breeder villager spawn. Looking through other examples of villager json files, I noticed it was the only villager with two skins (many trainers had multiple skins, but not villagers). 

I assumed the fault was mine for assuming villagers could have multiple skins so I chose to remove one so like other villagers it would have only one skin and hopefully pokemon breeder villagers would spawn in the next version of pixelmon. It may be possible that they are spawning, but I went through a pretty sizeable amount to never encounter one. Again- I assumed it was a mistake on my part including multiple skins- not a fault of the engine processing these files.

**Comment by AnonymousRandomPerson** [comment]
https://github.com/Pixelmon/NPCProject/commit/0a38ae35cd348c2af0a0e03dd23fe19d9603b4c4

It coincidentally happened to have two skins but that wasn't the issue. The actual issue has been fixed.

**Comment by TheOmniAdam** [comment]
If this is fixed than this change can be reverted.

**Pull request closed without merging**
