### PR TITLE
More villagers, more trainers, skin tweaks

### PR DESCRIPTION
**Pull request by PetitChouFleur**
- Four villager types, five skins (Policeman, Rancher, Rich Boy, Scary Man ("Cueball" & "Street Thug" variants))
- Dialogue for the four new types of villager, plus the forgotten dialogue for Battle Girl
- Added trainers: Rancher, Policeman, Scientist (F)
- added a reference to the Rich Boy skin now that there's one
- corrected the Pokéfan name into Pokémaniac, considering the trainer file names?
- Improved readability of faces (Black Belt, Hex Maniac, Hiker, Pokéfan (F), Policeman)

### CODE REVIEW

**Comment by PetitChouFleur** [comment]
Ah, I've just realised there's a mistake in my npcs.json commit. The skin for the ScientistWoman class is "scientist_f", not "scientistwoman". I don't know whether to cancel my pull request or do a quick patch later. I'll probably do the latter.
Besides, I don't know if trainer classes can have underscores in them, hence why that trainer's called that, unlike the villager-type scientist. I played it safe. Maybe my concerns were unfounded.

**Comment by isiliden** [comment]
You'll need to re-fork and add in your changes again due to merge conflicts in any case, so you'll be able to make corrections along the way.

**Comment by PetitChouFleur** [comment]
I'm not sure what you mean, is this pull request of mine invalid due to merge conflicts (as in, I didn't fork from the latest version or something)?
Either way I'm planning to add more stuff later, which means that I'll end up doing more commits and I can eventually fix the mistake. I was just concerned I'd make it a drag for you holders of the merging powers.

**Comment by PetitChouFleur** [comment]
All right, I've fixed my conflicts. I'll cancel this pull request and submit my changes again later! Sorry :) Still a bit of a Github newbie here.

**Pull request closed without merging**
